### ISSUE TITLE
problem warning iptables

### ISSUE THREAD

**Issue by agentichigo** [cloudex99/Destiny-2-Matchmaking-Firewall#4]
hello 

nice job i have a problem when i launch the matchmaking i never match with the second host i wait 5 minutes and i have an error because nobody match with me 
if invite second host in my fireteam works 
where I am mistaken if you have a idea to help me 
sorry for my english i am young belgian 15 old and i like programming

root@****i:~# sudo bash d2firewall.sh -a setup
Setting up firewall rules.
# Warning: iptables-legacy tables present, use iptables-legacy-save to see them
Enter your platform xbox, psn, steam: xbox
Enter your network/netmask: 10.42.0.1/24
Would you like to sniff the ID automatically?(psn/xbox/steam) y/n: y
Press any key to stop sniffing. DO NOT CTRL C
E876C*************************************A4A5A
E67CC*************************************A026C
# Warning: iptables-legacy tables present, use iptables-legacy-save to see them
Setup is complete and matchmaking firewall is now active.

**Comment by cloudex99** [comment]
The warning is not the problem. But update the script and it should not appear again. Matchmaking is slow due to various external factors. The higher the population in an activity the longer it will take to matchmake. Try a less popular strike for a test run.

**Comment by agentichigo** [comment]
now 1 min for match with my second console very good work thx
